@startuml

title TutorAccountController

start
:HTTP-запрос;

if (URL: /account) then (Да)
  :Отобразить страницу личного кабинета;
else if (URL: /account/update) then (Да)
  :Обработать POST-запрос на обновление данных учетной записи;
  if (Данные введены корректно?) then (Да)
    :Обновить данные учетной записи;
    :Отобразить страницу с сообщением об успешном обновлении данных;
  else (Нет)
    :Отобразить страницу с сообщением об ошибке ввода данных;
  endif
else if (URL: /account/update/personal) then (Да)
  :Обработать POST-запрос на обновление персональных данных;
  if (Данные введены корректно?) then (Да)
    :Обновить персональные данные;
    :Отобразить страницу с сообщением об успешном обновлении персональных данных;
  else (Нет)
    :Отобразить страницу с сообщением об ошибке ввода данных;
  endif
else if (URL: /account/update/address) then (Да)
  :Обработать POST-запрос на обновление адресных данных;
  if (Данные введены корректно?) then (Да)
    :Обновить адресные данные;
    :Отобразить страницу с сообщением об успешном обновлении адресных данных;
  else (Нет)
    :Отобразить страницу с сообщением об ошибке ввода данных;
  endif
else
  :Отобразить страницу с сообщением об ошибке недопустимого URL;
endif

stop

@enduml