@startuml
[*] --> Инициализация

Инициализация --> Ввод_данных : Пользователь инициирует добавление комментария

Ввод_данных --> Проверка_данных : Данные о комментарии введены

Проверка_данных --> Ошибка_ввода : Ошибка в данных[]
Проверка_данных --> Состояние_комментария_на_сервере : Данные корректны[]

Ошибка_ввода --> Ввод_данных : Исправить данные



state Состояние_комментария_на_сервере {
    [*] --> Ожидание_сохранения
    Ожидание_сохранения --> Сохранение : Сохранение комментария
    Сохранение --> Успех : Комментарий сохранен[]
    Сохранение --> Ошибка_сервиса : Ошибка при сохранении[]
    Ошибка_сервиса --> [*] : Завершение с ошибкой
    Успех --> [*] : Успешное завершение
}

Состояние_комментария_на_сервере --> [*] : Завершение процесса


@enduml