spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor_service
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tutormatchserver@gmail.com
    password:  yauj afmb dbgz ugcu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org.springframework.security: DEBUG
#    org.hibernate: DEBUG