spring:
datasource:
url: jdbc:postgresql://localhost:5432/db_name
username: your_username
password: your_password
jpa:
database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
ddl-auto: update
show-sql: true
