spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor_service
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org.springframework.security: DEBUG
#    org.hibernate: DEBUG