@startuml
left to right direction
actor Менеджер
actor Команда_разработки
actor Заказчик

rectangle "Система планирования на базе автоматизированной системы" {
  usecase "Создать задачу" as Создать_задачу
  usecase "Назначить ответственного" as Назначить_ответственного
  usecase "Установить дедлайн" as Установить_дедлайн
  usecase "Отслеживать прогресс" as Отслеживать_прогресс
  usecase "Добавить комментарии" as Добавить_комментарии
  usecase "Рассчитать трудозатраты" as Рассчитать_трудозатраты
  usecase "Управлять ресурсами" as Управлять_ресурсами
  usecase "Составить график работы" as Составить_график_работы
  usecase "Составить отчет" as Составить_отчет

  Рассчитать_трудозатраты ..> Составить_график_работы : include
  Рассчитать_трудозатраты ..> Составить_отчет : include

  Менеджер --> Создать_задачу
  Менеджер --> Назначить_ответственного
  Менеджер --> Установить_дедлайн
  Команда_разработки --> Отслеживать_прогресс
  Команда_разработки --> Добавить_комментарии
  Менеджер --> Рассчитать_трудозатраты
  Менеджер --> Управлять_ресурсами
  Заказчик --> Добавить_комментарии
  Заказчик --> Отслеживать_прогресс
  Менеджер --> Отслеживать_прогресс
}
@enduml

